version: '3'

services:
  web:
    container_name: galleryweb
    image: tripadvisorgallery
    build: .
    depends_on:
      - 'db'
    links:
      - 'db'
    ports:
      - '9999:9999'
    expose:
      - '9999'
  db:
    container_name: gallerydb
    image: tripadvisorsql
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    build: ./db
    ports:
      - '3306:3306'
    expose:
      - '3306'